apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: letsencrypt-companion
  name: letsencrypt-companion
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: letsencrypt-companion
status:
  loadBalancer: {}
