apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    io.kompose.service: app
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - image: ' '
        name: nextcloud-fpm
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/apps
          name: app-claim0
        - mountPath: /var/www/html/config
          name: app-claim1
        - mountPath: /var/www/html/data
          name: app-claim2
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
      - name: app-claim1
        persistentVolumeClaim:
          claimName: app-claim1
      - name: app-claim2
        persistentVolumeClaim:
          claimName: app-claim2
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nextcloud-fpm
      from:
        kind: ImageStreamTag
        name: app:fpm
    type: ImageChange
status: {}
