apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: collabora
  name: collabora
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: collabora/code
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
