apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: letsencrypt-companion
  name: letsencrypt-companion
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
