apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: jwilder/nginx-proxy
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
