apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    io.kompose.service: web
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
        - name: VIRTUAL_NETWORK
          value: nginx-proxy
        - name: VIRTUAL_PORT
          value: "80"
        - name: LETSENCRYPT_HOST
        - name: LETSENCRYPT_EMAIL
        image: ' '
        name: nextcloud-webserver
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: web-claim0
          readOnly: true
        - mountPath: /var/www/html/apps
          name: app-claim0
        - mountPath: /var/www/html/config
          name: app-claim1
        - mountPath: /var/www/html/data
          name: app-claim2
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
          readOnly: true
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
      - name: app-claim1
        persistentVolumeClaim:
          claimName: app-claim1
      - name: app-claim2
        persistentVolumeClaim:
          claimName: app-claim2
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nextcloud-webserver
      from:
        kind: ImageStreamTag
        name: web:latest
    type: ImageChange
status: {}
