apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - image: nextcloud:fpm
        name: nextcloud-fpm
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/apps
          name: app-claim0
        - mountPath: /var/www/html/config
          name: app-claim1
        - mountPath: /var/www/html/data
          name: app-claim2
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
      - name: app-claim1
        persistentVolumeClaim:
          claimName: app-claim1
      - name: app-claim2
        persistentVolumeClaim:
          claimName: app-claim2
status: {}
